# Site settings
title: Nick Ceglia
email: nickceglia@gmail.com
description: > # Personal website of Nick Ceglia - Software Engineer, Researcher, and Open Source Contributor
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://nceglia.github.io" # the base hostname & protocol for your site
twitter_username: nceglia
github_username: nceglia
linkedin_username: nceglia

# Build settings
markdown: kramdown
