# Site settings
title: Nick Ceglia's blog
email: nickceglia@gmail.com
description: > #This is Nick Ceglia's blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: nceglia
github_username:  nceglia

# Build settings
markdown: kramdown
